"""empty message

Revision ID: c27af1439266
Revises: 627a1f5f2b94
Create Date: 2019-05-07 10:13:10.353096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27af1439266'
down_revision = '627a1f5f2b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excerpt', sa.Column('testdata', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excerpt', 'testdata')
    # ### end Alembic commands ###
